name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build_push
      run: |
        docker build -t ghcr.io/${{ github.actor }}/longest-subdir-finder:latest .
        docker push ghcr.io/${{ github.actor }}/longest-subdir-finder:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        echo "This is where the tests would run. Consider adding a few mock directiories to test the script."

  # The container can also be deployed to a Kubernetes cluster or a server, but the infrastructure is not given in this case.
